chore: update nodejs install method

diff --git a/ectl b/ectl
--- a/ectl
+++ b/ectl
@@ -17,7 +17,17 @@ export GOLANG_VERSION=1.20.1
 export NVIM_VERSION=0.5.1
 export OPENSSL_VERSION=1.1.1q
 export PYTHON3_VERSION=3.11.4
-export NODEJS_VERSION=17.9.1
+export NODEJS_VERSION=20.6.1
+
+# tools function
+command_exists() {
+  command -v "$@" > /dev/null 2>&1
+}
+
+fmt_error() {
+  printf '%sError: %s%s\n' "${FMT_BOLD}${FMT_RED}" "$*" "$FMT_RESET" >&2
+}
+
 
 function set_chrony() {
   # vim /etc/chrony.conf
@@ -207,40 +217,43 @@ EOF
   fi
 }
 
-function install_nodejs() {
+install_nodejs() {
   filename=node-v${NODEJS_VERSION}-linux-x64.tar.xz
-  function do_nodejs_download() {
-    curl -L https://nodejs.org/dist/v${NODEJS_VERSION}/node-v${NODEJS_VERSION}-linux-x64.tar.xz -O ${filename}
+  do_nodejs_download() {
+    curl -L https://nodejs.org/dist/v${NODEJS_VERSION}/node-v${NODEJS_VERSION}-linux-x64.tar.xz -O /tmp/${filename}
   }
-  function do_nodejs_install() {
-    if [[ -f $filename ]];then
-      tar -xf ${filename} -C /usr/local
-      rm -f ${filename}
-      cd /usr/local
-      mv node-v${NODEJS_VERSION}-linux-x64 node
+  do_nodejs_setup() {
+    cat <<EOF
+手动执行以下命令将node添加到Path及切换淘宝源：
+echo 'export PATH="\$PATH:/usr/local/node/bin"' >> /etc/profile
+npm config set registry https://registry.npmmirror.com 
+source /etc/profile
+EOF
+  }
+  do_nodejs_install() {
+    if [[ -f /tmp/$filename ]];then
+      tar -xf /tmp/${filename} -C /usr/local
+      rm -f /tmp/${filename}
+      mv /usr/local/node-v${NODEJS_VERSION}-linux-x64 /usr/local/node
       echo -e "\033[33m[INFO]nodejs${NODEJS_VERSION}安装完成.\033[0m"
+      do_nodejs_setup
     else
-      do_nodejs_download
       do_nodejs_install
     fi
   }
-  if [[ -d /usr/local/node ]]; then
+  if command_exists node; then
     version=$(node -v)
-    read -p "[INFO]$version 已存在,是否覆盖安装? yes/no." param
+    read -p "[INFO]node $version 已存在,是否覆盖安装? yes/no." param
     if [ $param == "yes" ]; then
-      rm -rf /usr/local/node
+      node_folder_path=$(which node)
+      rm -rf ${node_folder_path:0:-9}
       do_nodejs_install
     else
+      do_nodejs_setup
       exit 0
     fi
   else
     do_nodejs_install
-    echo "# nodejs settings" >>/etc/profile
-    echo "export PATH="$PATH:/usr/local/node/bin"" >>/etc/profile
-    echo 'alias for cnpm\nalias cnpm="npm --registry=https://registry.npmmirror.com \
-  --cache=$HOME/.npm/.cache/cnpm \
-  --disturl=https://npmmirror.com/mirrors/node \
-  --userconfig=$HOME/.cnpmrc"' >>~/.zshrc && source ~/.zshrc
   fi
 }
 
