chore: clean unuse function

diff --git a/ectl b/ectl
--- a/ectl
+++ b/ectl
@@ -13,121 +13,29 @@
 set -euo pipefail
 
 # default version, can be overridden by cmd line options
-export DOCKER_VER=18.09.7
-export REGISTRY_MIRROR=CN
-export KUBEASZ_VER=2.0.2
 export GOLANG_VERSION=1.18.3
 export NVIM_VERSION=0.5.1
 export OPENSSL_VERSION=1.1.1q
 export PYTHON3_VERSION=3.10.3
 
-function install_docker() {
-  # check if a container runtime is already installed
-  systemctl status docker|grep Active|grep -q running && { echo "[WARN] docker is already running."; return 0; }
-  systemctl status containerd|grep Active|grep -q running && { echo "[ERROR] containerd is running, unsupported."; exit 1; }
-  DOCKER_URL="https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/static/stable/x86_64/docker-${DOCKER_VER}.tgz"
-  mkdir -p /opt/kube/bin /etc/docker /etc/ansible/down
-  
-  if [[ -f "/etc/ansible/down/docker-${DOCKER_VER}.tgz" ]];then
-    echo "[INFO] docker binaries already existed"
-  else
-    echo -e "[INFO] \033[33mdownloading docker binaries\033[0m $DOCKER_VER"
-    if [[ -e /usr/bin/curl ]];then
-      curl -C- -O --retry 3 "$DOCKER_URL" || { echo "[ERROR] downloading docker failed"; exit 1; }
-    else
-      wget -c "$DOCKER_URL" || { echo "[ERROR] downloading docker failed"; exit 1; }
-    fi
-    mv ./docker-${DOCKER_VER}.tgz /etc/ansible/down
-  fi
-
-  tar zxf /etc/ansible/down/docker-${DOCKER_VER}.tgz -C /etc/ansible/down && \
-  mv /etc/ansible/down/docker/* /opt/kube/bin && \
-  ln -sf /opt/kube/bin/docker /bin/docker
-
-  echo "[INFO] generate docker service file"
-  cat > /etc/systemd/system/docker.service << EOF
-[Unit]
-Description=Docker Application Container Engine
-Documentation=http://docs.docker.io
-[Service]
-Environment="PATH=/opt/kube/bin:/bin:/sbin:/usr/bin:/usr/sbin"
-ExecStart=/opt/kube/bin/dockerd
-ExecStartPost=/sbin/iptables -I FORWARD -s 0.0.0.0/0 -j ACCEPT
-ExecReload=/bin/kill -s HUP \$MAINPID
-Restart=on-failure
-RestartSec=5
-LimitNOFILE=infinity
-LimitNPROC=infinity
-LimitCORE=infinity
-Delegate=yes
-KillMode=process
-[Install]
-WantedBy=multi-user.target
-EOF
-
-  # configuration for dockerd
-  echo "[INFO] generate docker config file"
-  if [[ "$REGISTRY_MIRROR" == CN ]];then
-    echo "[INFO] prepare register mirror for $REGISTRY_MIRROR"
-    cat > /etc/docker/daemon.json << EOF
-{
-  "registry-mirrors": [
-    "https://dockerhub.azk8s.cn",
-    "https://docker.mirrors.ustc.edu.cn",
-    "http://hub-mirror.c.163.com"
-  ],
-  "max-concurrent-downloads": 10,
-  "log-driver": "json-file",
-  "log-level": "warn",
-  "log-opts": {
-    "max-size": "10m",
-    "max-file": "3"
-    },
-  "data-root": "/var/lib/docker"
-}
-EOF
-  else
-    echo "[INFO] standard config without registry mirrors"
-    cat > /etc/docker/daemon.json << EOF
-{
-  "max-concurrent-downloads": 10,
-  "log-driver": "json-file",
-  "log-level": "warn",
-  "log-opts": {
-    "max-size": "10m",
-    "max-file": "3"
-    },
-  "data-root": "/var/lib/docker"
-}
-EOF
-  fi
-
-  if [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
-    echo "[INFO] turn off selinux in CentOS/Redhat"
-    setenforce 0
-    echo "SELINUX=disabled" > /etc/selinux/config
-  fi
-
-  echo "[INFO] enable and start docker"
-  systemctl enable docker
-  systemctl daemon-reload && systemctl restart docker && sleep 8
-}
-
-function get_kubeasz() {
-  # check if kubeasz is already existed
-  [[ -d "/etc/ansible/roles/kube-node" ]] && { echo "[WARN] kubeasz already existed"; return 0; }
-  echo -e "[INFO] \033[33mdownloading kubeasz\033[0m $KUBEASZ_VER"
-}
-
 function set_chrony() {
-# vim /etc/chrony.conf
-# 常用命令
-# chronyc source -v
-# systemctl restart chronyd
+  # vim /etc/chrony.conf
+  # 常用命令
+  # chronyc source -v
+  # systemctl restart chronyd
   exit 0
 }
 
 function install_docker_online() {
+  # check if a container runtime is already installed
+  systemctl status docker | grep Active | grep -q running && {
+    echo "[WARN] docker is already running."
+    return 0
+  }
+  systemctl status containerd | grep Active | grep -q running && {
+    echo "[ERROR] containerd is running, unsupported."
+    exit 1
+  }
   # step 1: 安装必要的一些系统工具
   yum install -y yum-utils device-mapper-persistent-data lvm2
   # Step 2: 添加软件源信息
@@ -139,7 +47,7 @@ function install_docker_online() {
   # Step 5: 设置Dokcer服务开启启用
   systemctl enable docker
   # Step 6: 配置Dokcer加速器
-  cat > /etc/docker/daemon.json << EOF
+  cat >/etc/docker/daemon.json <<EOF
 {
   "registry-mirrors": [
     "https://dockerhub.azk8s.cn",
@@ -173,8 +81,8 @@ function package_docker_latest() {
 # 脚本执行完以后需重启机器
 function update_kernel() {
   rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
-  if [ -z  `rpm -qa|grep elrepo-release` ]; then
-    yum install https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm 
+  if [ -z $(rpm -qa | grep elrepo-release) ]; then
+    yum install https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
   else
     yum --disablerepo=\* --enablerepo=elrepo-kernel install -y kernel-lt.x86_64
     yum remove kernel-tools-libs.x86_64 kernel-tools.x86_64 -y
@@ -193,7 +101,7 @@ function init_git_config() {
 
 function init_docker_tpl() {
   mkdir $1
-  cat >> ./$1/Makefile << EOF
+  cat >>./$1/Makefile <<EOF
 NAME="$1"
 
 up:
@@ -207,7 +115,7 @@ logs:
 exec:
 	docker exec -it \${NAME} sh
 EOF
-  cat >> ./$1/docker-compose.yaml << EOF
+  cat >>./$1/docker-compose.yaml <<EOF
 version: "3.7"
 services:
 
@@ -226,7 +134,7 @@ networks:
   internal:
     external: true
 EOF
-echo -e "\e[33mSuccess!\e[0m"
+  echo -e "\e[33mSuccess!\e[0m"
 }
 
 function install_neovim() {
@@ -241,13 +149,12 @@ function install_neovim() {
 }
 
 function install_ohmyzsh() {
-  if [[ -d /root/.oh-my-zsh ]];
-  then
+  if [[ -d /root/.oh-my-zsh ]]; then
     echo -e "\033[33m[INFO]oh my zsh already installed.\033[0m"
     echo -e "\033[33m[INFO]plugins setup start.\033[0m"
     git clone https://hub.fastgit.xyz/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
     sed -i 's/plugins=(git)/plugins=(\n    git\n    zsh-autosuggestions\n)/g' ~/.zshrc
-cat >> ~/.zshrc << EOF
+    cat >>~/.zshrc <<EOF
 bindkey ',' autosuggest-accept
 export TERM=xterm-256color
 ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=yellow,bg=bold"
@@ -256,9 +163,9 @@ EOF
     chsh -s /bin/zsh
     source ~/.zshrc
   else
-  yum install -y zsh
-  zsh --version
-  REMOTE=https://hub.fastgit.xyz/ohmyzsh/ohmyzsh.git sh -c "$(wget -O- https://raw.fastgit.org/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+    yum install -y zsh
+    zsh --version
+    REMOTE=https://hub.fastgit.xyz/ohmyzsh/ohmyzsh.git sh -c "$(wget -O- https://raw.fastgit.org/ohmyzsh/ohmyzsh/master/tools/install.sh)"
   fi
 }
 
@@ -267,7 +174,7 @@ function install_golang() {
   cd /usr/local
   tar -zxvf go${GOLANG_VERSION}.linux-amd64.tar.gz
   rm -f go${GOLANG_VERSION}.linux-amd64.tar.gz
-cat  >> /etc/profile << EOF
+  cat >>/etc/profile <<EOF
 
 # 配置环境变量
 export GOROOT="/usr/local/go"
@@ -277,7 +184,7 @@ export PATH="\$PATH:\$GOROOT/bin:\$GOPATH"
 export GO111MODULE="on"
 export GOPROXY="https://goproxy.io"
 EOF
-source /etc/profile
+  source /etc/profile
 }
 
 function install_openssl() {
@@ -292,7 +199,7 @@ function install_openssl() {
 }
 
 function install_python3() {
-  if [[ -f ./assets/Python-${PYTHON3_VERSION}.tgz ]];then
+  if [[ -f ./assets/Python-${PYTHON3_VERSION}.tgz ]]; then
     echo -e "\033[33m[INFO]Python-${PYTHON3_VERSION}.tgz exist.\033[0m"
     echo -e "\033[33m[INFO]start install.\033[0m"
     tar -xvf ./assets/Python-${PYTHON3_VERSION}.tgz -C /opt/
@@ -312,7 +219,7 @@ function install_python3() {
 
 #--- Usage Func ------------------------------------
 function usage() {
-cat <<  EOF
+  cat <<EOF
 Usage: ectl [options] [args]
   options: -{h}
   
@@ -331,14 +238,14 @@ EOF
 function main() {
   if [ "$#" == 0 ]; then
     usage
-  elif [  "$1" == "-h" ];then
+  elif [ "$1" == "-h" ]; then
     usage
   elif [[ "$1" == "-i" && "$#" == 2 ]]; then
     init_docker_tpl "$2"
   elif [[ "$1" == "install" ]]; then
     if [[ "$2" == "docker" ]]; then
       install_docker_online
-    elif [[  "$2" == "neovim"  ]]; then
+    elif [[ "$2" == "neovim" ]]; then
       install_neovim
     elif [[ "$2" == "zsh" ]]; then
       install_ohmyzsh
